-- Converted database schema from Oracle to MySQL
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(100),
    PRICE DECIMAL(10, 2)
);

CREATE TABLE USERS (
    USER_ID INT NOT NULL,
    USERNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(50)
);

CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL,
    USER_ID INT,
    PRODUCT_ID INT,
    ORDER_DATE DATE
);

CREATE TABLE HOLIDAYS (
    HOLIDAY_ID INT NOT NULL,
    HOLIDAY_NAME VARCHAR(100),
    HOLIDAY_DATE DATE
);

CREATE TABLE MYSQL_ORDERS (
    ORDER_ID DECIMAL(10, 0) NOT NULL,
    USER_ID DECIMAL(10, 0),
    CUSTOMER_ID DECIMAL(10, 0),
    PRODUCT_ID DECIMAL(10, 0),
    ORDER_DATE DATE NOT NULL,
    QUANTITY DECIMAL(10, 0) NOT NULL,
    TOTAL_PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE MYSQLORDERS (
    ORDER_ID DECIMAL(10, 0) NOT NULL,
    USER_ID DECIMAL(10, 0),
    CUSTOMER_ID DECIMAL(10, 0),
    PRODUCT_ID DECIMAL(10, 0),
    ORDER_DATE DATE NOT NULL,
    QUANTITY DECIMAL(10, 0) NOT NULL,
    TOTAL_PRICE DECIMAL(10, 2) NOT NULL
);


