-- Schema for table PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR2(100),
    PRICE NUMBER(10,2)
);

-- Schema for table USERS
CREATE TABLE USERS (
    USER_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(50)
);

-- Schema for table ORDERS
CREATE TABLE ORDERS (
    ORDER_ID NUMBER NOT NULL,
    USER_ID NUMBER,
    PRODUCT_ID NUMBER,
    ORDER_DATE DATE(7)
);

-- Schema for table HOLIDAYS
CREATE TABLE HOLIDAYS (
    HOLIDAY_ID NUMBER NOT NULL,
    HOLIDAY_NAME VARCHAR2(100),
    HOLIDAY_DATE DATE(7)
);

-- Schema for table MYSQL_ORDERS
CREATE TABLE MYSQL_ORDERS (
    ORDER_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    CUSTOMER_ID NUMBER(10),
    PRODUCT_ID NUMBER(10),
    ORDER_DATE DATE(7) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    TOTAL_PRICE NUMBER(10,2) NOT NULL
);

-- Schema for table MYSQLORDERS
CREATE TABLE MYSQLORDERS (
    ORDER_ID NUMBER(10) NOT NULL,
    USER_ID NUMBER(10),
    CUSTOMER_ID NUMBER(10),
    PRODUCT_ID NUMBER(10),
    ORDER_DATE DATE(7) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    TOTAL_PRICE NUMBER(10,2) NOT NULL
);

